# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-04-19 10:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Query', max_length=30)),
                ('email', models.CharField(default='User', max_length=30)),
                ('message', models.TextField(max_length=250)),
            ],
        ),
    ]
