# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-03-22 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200321_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.CharField(default='User', max_length=30),
        ),
    ]
