# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-03-22 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200322_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='XYfitness image', upload_to='images'),
        ),
    ]
