# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-03-22 22:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_profile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='User Image', upload_to='images'),
        ),
    ]
