# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-04-21 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200322_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='images/4648398-blue-steel.jpg', upload_to='images'),
        ),
    ]
