# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-04-10 21:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='street_address1',
            field=models.CharField(blank=True, max_length=40, verbose_name='House name / apartment no.'),
        ),
        migrations.AlterField(
            model_name='order',
            name='street_address2',
            field=models.CharField(max_length=40, verbose_name='Townland'),
        ),
    ]
