# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-04-26 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_auto_20200410_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='county',
            field=models.CharField(max_length=40, verbose_name='County / city'),
        ),
        migrations.AlterField(
            model_name='order',
            name='street_address1',
            field=models.CharField(blank=True, max_length=40, verbose_name='House name / apartment no (optional)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='street_address2',
            field=models.CharField(max_length=40, verbose_name='Townland / street name'),
        ),
    ]
