# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-04-06 22:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_remove_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone_number',
            field=models.IntegerField(max_length=20),
        ),
    ]
