# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-04-07 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0007_auto_20200406_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlineitem',
            name='total',
            field=models.IntegerField(default='x amount'),
        ),
    ]
