# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-03-17 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='XYfitness image', upload_to='images')),
                ('author', models.CharField(default=' XYfitness Product', max_length=100)),
                ('content', models.TextField(max_length=250)),
            ],
        ),
    ]
