# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-04-04 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_remove_review_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='image1',
            field=models.ImageField(default='User before image', upload_to='images'),
        ),
        migrations.AddField(
            model_name='review',
            name='image2',
            field=models.ImageField(default='User after image', upload_to='images'),
        ),
    ]
