# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-04-04 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0008_auto_20200404_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='after_picture',
            field=models.ImageField(default='Only add the after pic if you want to!', upload_to='images'),
        ),
        migrations.AlterField(
            model_name='review',
            name='before_picture',
            field=models.ImageField(default='If you want to add a before pic you can do so here', upload_to='images'),
        ),
    ]
