# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-04-04 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0010_auto_20200404_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='after_picture',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='review',
            name='before_picture',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
