# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-04-06 10:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0011_auto_20200404_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='before_picture',
            field=models.ImageField(blank=True, upload_to='images', verbose_name='Before pic (only add these if you want to).'),
        ),
    ]
