# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-04-21 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0012_auto_20200406_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='image',
            field=models.ImageField(default='images/4648398-blue-steel.jpg', upload_to='images'),
        ),
    ]
