# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-03-18 22:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200316_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default='plan', max_length=30),
        ),
    ]
