# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-03-21 20:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(default='plan or apparel', max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default='XYfitness Product', max_length=100),
        ),
    ]
