# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-03-24 18:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20200324_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shirt_size',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], default='S', max_length=1),
        ),
    ]
