# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-03-30 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_remove_product_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsize',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('XS', 'Extra Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large')], default='choose size', max_length=100, verbose_name='size'),
        ),
        migrations.DeleteModel(
            name='ProductSize',
        ),
    ]
