# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-04-02 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_auto_20200330_1313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AddField(
            model_name='product',
            name='image1',
            field=models.ImageField(default='XYfitness image1', upload_to='images'),
        ),
        migrations.AddField(
            model_name='product',
            name='image2',
            field=models.ImageField(default='XYfitness image2', upload_to='images'),
        ),
        migrations.AddField(
            model_name='product',
            name='image3',
            field=models.ImageField(default='XYfitness image3', upload_to='images'),
        ),
    ]
