# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-04-20 11:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_auto_20200403_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='equipment',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(max_length=400),
        ),
    ]
