# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-04-21 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0030_auto_20200421_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='title',
            field=models.CharField(default='User Review', max_length=30),
        ),
    ]
